### ISSUE TITLE
source directory doesnt exist? issue compiling

### ISSUE THREAD

**Issue by zarosath** [blitz3d-ng/package#52]
CMake Error: The source directory "/home/william/b3d/build/llvm/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:106: recipe for target 'llvm' failed

ubuntu 18.04

**Comment by zarosath** [comment]
when cloning through git i ran into a problem, i ctrl+Z terminated the git cloning process and when i tried to clone through git again it had a problem so i deleted the b3d folder and cloned through git again.. i dont know if that is related to this issue.

**Comment by kfprimm** [comment]
Closing this because you opened a [discussion](https://github.com/blitz3d-ng/package/discussions/51) (the correct place for this).
